// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaFinale_week7_LIONETTO;

#nullable disable

namespace ProvaFinale_week7_LIONETTO.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220114092351_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProvaFinale_week7_LIONETTO.Models.Cliente", b =>
                {
                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength();

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CodiceFiscale");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("ProvaFinale_week7_LIONETTO.Models.Polizza", b =>
                {
                    b.Property<int>("NumeroPolizza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroPolizza"), 1L, 1);

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nchar(16)");

                    b.Property<DateTime>("DataStipula")
                        .HasColumnType("datetime2");

                    b.Property<float>("ImportoAssicurazione")
                        .HasColumnType("real");

                    b.Property<float>("RataMensile")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumeroPolizza");

                    b.HasIndex("CodiceFiscale");

                    b.ToTable("Polizza", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Polizza");
                });

            modelBuilder.Entity("ProvaFinale_week7_LIONETTO.Models.Furto", b =>
                {
                    b.HasBaseType("ProvaFinale_week7_LIONETTO.Models.Polizza");

                    b.Property<int>("PercentualeCopertura")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Furto");
                });

            modelBuilder.Entity("ProvaFinale_week7_LIONETTO.Models.RcAuto", b =>
                {
                    b.HasBaseType("ProvaFinale_week7_LIONETTO.Models.Polizza");

                    b.Property<int>("Cilindrata")
                        .HasColumnType("int");

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasDiscriminator().HasValue("RcAuto");
                });

            modelBuilder.Entity("ProvaFinale_week7_LIONETTO.Models.Vita", b =>
                {
                    b.HasBaseType("ProvaFinale_week7_LIONETTO.Models.Polizza");

                    b.Property<int>("AnniAssicurato")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Vita");
                });

            modelBuilder.Entity("ProvaFinale_week7_LIONETTO.Models.Polizza", b =>
                {
                    b.HasOne("ProvaFinale_week7_LIONETTO.Models.Cliente", "Cliente")
                        .WithMany("Polizze")
                        .HasForeignKey("CodiceFiscale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProvaFinale_week7_LIONETTO.Models.Cliente", b =>
                {
                    b.Navigation("Polizze");
                });
#pragma warning restore 612, 618
        }
    }
}
